"Scheme"
{
	"BaseSettings"
	{
		// scheme-specific colors
		"Border.Bright"								"Blank"	// the lit side of a control
		"Border.Dark"								"ehDarkerBlackColor"	// the dark/unlit side of a control
		"Border.Selection"							"ehAccentColor"	// the additional border color for displaying the default/selected button
		"Button.TextColor"							"ehWhiteColor"
		"Button.BgColor"							"ehDarkerBlackColor"
		"Button.ArmedTextColor"						"ehWhiteColor"
		"Button.ArmedBgColor"						"ehAccentColor"
		"Button.DepressedTextColor"					"ehWhiteColor"
		"Button.DepressedBgColor"					"ehAccentColor"
		"Button.FocusBorderColor"					"Blank"
		"Button.SelectedTextColor"					"ehAccentColor"
		"CheckButton.TextColor"						"ehWhiteColor"
		"CheckButton.SelectedTextColor"				"ehAccentColor"
		"CheckButton.BgColor"						"ehBlackColor"
		"CheckButton.HighlightFgColor"				"ehAccentColor"
		"CheckButton.ArmedBgColor"					"Blank"
		"CheckButton.DepressedBgColor"				"Blank"
		"CheckButton.Border1"						"ehWhiteColor"	// the left checkbutton border
		"CheckButton.Border2"						"ehWhiteColor"	// the right checkbutton border
		"CheckButton.Check"							"ehAccentColor"	// color of the check itself
		"CheckButton.DisabledBgColor"				"ehGrayColor"
		"ToggleButton.SelectedTextColor"			"ehWhiteColor"
		"ComboBoxButton.ArrowColor"					"ehWhiteColor"
		"ComboBoxButton.ArmedArrowColor"			"ehAccentColor"
		"ComboBoxButton.BgColor"					"Blank"
		"ComboBoxButton.DisabledBgColor"			"Blank"
		"RadioButton.TextColor"						"ehWhiteColor"
		"RadioButton.SelectedTextColor"				"ehAccentColor"
		"RadioButton.ArmedTextColor"				"ehAccentColor"
		"Frame.BgColor"								"ehBlackColor"
		"Frame.OutOfFocusBgColor"					"ehBackgroundMenuColor"
		"FrameGrip.Color1"							"TFTanMedium"
		"FrameGrip.Color2"							"TFDarkBrown"
		"FrameTitleButton.FgColor"					"TFTanBright"
		"FrameTitleBar.Font"						"ehFont18"
		"FrameTitleBar.TextColor"					"ehWhiteColor"
		"FrameTitleBar.BgColor"						"ehAccentColor"
		"FrameTitleBar.DisabledTextColor"			"TFTanLight"
		"Label.TextDullColor"						"ehGrayColor"
		"Label.TextColor"							"ehWhiteColor"
		"Label.TextBrightColor"						"ehWhiteColor"
		"Label.SelectedTextColor"					"ehWhiteColor"
		"Label.BgColor"								"Blank"
		"Label.DisabledFgColor1"					"ehGrayColor"
		"Label.DisabledFgColor2"					"Blank"
		"ListPanel.TextColor"						"ehWhiteColor"
		"ListPanel.BgColor"							"ListBG"
		"ListPanel.SelectedBgColor"					"ehAccentColor"
		"ListPanel.SelectedOutOfFocusBgColor"		"ehAccentTransparentColor"
		"MainMenu.TextColor"						"ehWhiteColor"
		"MainMenu.ArmedTextColor"					"ehWhiteColor"
		"MainMenu.Inset"							"32"
		"Menu.TextInset"							"6"
		"Menu.FgColor"								"ehWhiteColor"
		"Menu.BgColor"								"ehBlackColor"
		"Menu.ArmedFgColor"							"ehWhiteColor"
		"Menu.ArmedBgColor"							"ehAccentColor"
		"Menu.DividerColor"							"ehBlackColor"
		"ScrollBarButton.FgColor"					"ehAccentColor"
		"ScrollBarButton.BgColor"					"Blank"
		"ScrollBarButton.ArmedFgColor"				"ehBlackColor"
		"ScrollBarButton.ArmedBgColor"				"ehAccentColor"
		"ScrollBarButton.DepressedFgColor"			"ehBlackColor"
		"ScrollBarButton.DepressedBgColor"			"ehAccentColor"
		"ScrollBarSlider.BgColor"					"ehBlackColor"	// this isn't really used
		"ScrollBarSlider.FgColor"					"ehAccentColor"	// handle with which the slider is grabbed
		"Slider.NobColor"							"TFTanLight"
		"Slider.TextColor"							"ehWhiteColor"
		"Slider.TrackColor"							"ListBG"
		"Slider.DisabledTextColor1"					"ehGrayColor"
		"Slider.DisabledTextColor2"					"Blank"
		"TextEntry.TextColor"						"ehWhiteColor"
		"TextEntry.DisabledTextColor"				"ehWhiteColor"
		"TextEntry.SelectedBgColor"					"ehAccentColor"
	}
}