"#dev/reload.res"
{
	"ReloadMenuButton"
	{
		"ControlName"				"CExButton"
		"fieldName"					"ReloadMenuButton"
		"xpos"						"r50"
		"ypos"						"50"
		"zpos"						"9999"
		"wide"						"45"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
		"proportionaltoparent"		"1"
		"labelText"					"RMenu"
		"font"						"HudFontSmallestBold"
		"textAlignment"				"center"
		"Command"					"engine toggle mat_aaquality"
	}
	"ReloadScheme"
	{
		"ControlName"				"CExButton"
		"fieldName"					"ReloadScheme"
		"xpos"						"0"
		"ypos"						"4"
		"zpos"						"9999"
		"wide"						"45"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
		"proportionaltoparent"		"1"
		"labelText"					"RScheme"
		"font"						"HudFontSmallestBold"
		"textAlignment"				"center"
		"Command"					"reloadscheme"
		"pin_to_sibling"			"ReloadMenuButton"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"ReloadMaterials"
	{
		"ControlName"				"CExButton"
		"fieldName"					"ReloadMaterials"
		"xpos"						"0"
		"ypos"						"4"
		"zpos"						"9999"
		"wide"						"45"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
		"proportionaltoparent"		"1"
		"labelText"					"RMat"
		"font"						"HudFontSmallestBold"
		"textAlignment"				"center"
		"Command"					"engine mat_reloadallmaterials"
		"pin_to_sibling"			"ReloadScheme"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
	"VguiTree"
	{
		"ControlName"				"CExButton"
		"fieldName"					"VguiTree"
		"xpos"						"0"
		"ypos"						"4"
		"zpos"						"9999"
		"wide"						"45"
		"tall"						"15"
		"visible"					"1"
		"enabled"					"1"
		"proportionaltoparent"		"1"
		"labelText"					"tree"
		"font"						"HudFontSmallestBold"
		"textAlignment"				"center"
		"Command"					"engine sv_cheats 1; vgui_drawtree 1"
		"pin_to_sibling"			"ReloadMaterials"
		"pin_corner_to_sibling"		"0"
		"pin_to_sibling_corner"		"2"
	}
}