"Scheme"
{
	"BaseSettings"
	{
		// vgui_controls color specifications
		"Border.Bright"											"200 200 200 196"	// the lit side of a control
		"Border.Dark"											"40 40 40 196"	// the dark/unlit side of a control
		"Border.Selection"										"0 0 0 196"	// the additional border color for displaying the default/selected button
		"Button.TextColor"										"White"
		"Button.BgColor"										"Blank"
		"Button.ArmedTextColor"									"White"
		"Button.ArmedBgColor"									"Blank"
		"Button.DepressedTextColor"								"White"
		"Button.DepressedBgColor"								"Blank"
		"Button.FocusBorderColor"								"Black"
		"CheckButton.TextColor"									"OffWhite"
		"CheckButton.SelectedTextColor"							"White"
		"CheckButton.BgColor"									"TransparentBlack"
		"CheckButton.Border1"									"Border.Dark"	// the left checkbutton border
		"CheckButton.Border2"									"Border.Bright"	// the right checkbutton border
		"CheckButton.Check"										"White"	// color of the check itself
		"ComboBoxButton.ArrowColor"								"DullWhite"
		"ComboBoxButton.ArmedArrowColor"						"White"
		"ComboBoxButton.BgColor"								"Blank"
		"ComboBoxButton.DisabledBgColor"						"Blank"
		"Chat.TypingText"										"ehWhiteColor"
		"Frame.TitleTextInsetX"									"16"
		"Frame.ClientInsetX"									"8"
		"Frame.ClientInsetY"									"6"
		"Frame.BgColor"											"160 160 160 128" [$WIN32]
		"Frame.OutOfFocusBgColor"								"160 160 160 32" [$WIN32]
		"Frame.FocusTransitionEffectTime"						"0.3"	// time it takes for a window to fade in/out on focus/out of focus
		"Frame.TransitionEffectTime"							"0.3"	// time it takes for a window to fade in/out on open/close
		"Frame.AutoSnapRange"									"0"
		"FrameGrip.Color1"										"200 200 200 196"
		"FrameGrip.Color2"										"0 0 0 196"
		"FrameTitleButton.FgColor"								"200 200 200 196"
		"FrameTitleButton.BgColor"								"Blank"
		"FrameTitleButton.DisabledFgColor"						"255 255 255 192"
		"FrameTitleButton.DisabledBgColor"						"Blank"
		"FrameSystemButton.FgColor"								"Blank"
		"FrameSystemButton.BgColor"								"Blank"
		"FrameSystemButton.Icon"								""
		"FrameSystemButton.DisabledIcon"						""
		"FrameTitleBar.Font"									"UiBold" [$WIN32]
		"FrameTitleBar.Font"									"DefaultLarge" [$WIN32]
		"FrameTitleBar.TextColor"								"White"
		"FrameTitleBar.BgColor"									"Blank"
		"FrameTitleBar.DisabledTextColor"						"255 255 255 192"
		"FrameTitleBar.DisabledBgColor"							"Blank"
		"GraphPanel.FgColor"									"White"
		"GraphPanel.BgColor"									"TransparentBlack"
		"Label.TextDullColor"									"DullWhite"
		"Label.TextColor"										"OffWhite"
		"Label.TextBrightColor"									"White"
		"Label.SelectedTextColor"								"White"
		"Label.BgColor"											"TransparentBlack"
		"Label.DisabledFgColor1"								"117 117 117 255"
		"Label.DisabledFgColor2"								"30 30 30 255"
		"ListPanel.TextColor"									"OffWhite"
		"ListPanel.TextBgColor"									"Blank"
		"ListPanel.BgColor"										"TransparentBlack"
		"ListPanel.SelectedTextColor"							"Black"
		"ListPanel.SelectedBgColor"								"Orange"
		"ListPanel.SelectedOutOfFocusBgColor"					"255 155 0 128"
		"ListPanel.EmptyListInfoTextColor"						"OffWhite"
		"Menu.TextColor"										"White"
		"Menu.BgColor"											"160 160 160 64"
		"Menu.ArmedTextColor"									"Black"
		"Menu.ArmedBgColor"										"Orange"
		"Menu.TextInset"										"6"
		"Panel.FgColor"											"Blank"
		"Panel.BgColor"											"DullWhite"
		"ProgressBar.FgColor"									"White"
		"ProgressBar.BgColor"									"TransparentBlack"
		"PropertySheet.TextColor"								"OffWhite"
		"PropertySheet.SelectedTextColor"						"White"
		"PropertySheet.TransitionEffectTime"					"0.25"	// time to change from one tab to another
		"RadioButton.TextColor"									"DullWhite"
		"RadioButton.SelectedTextColor"							"White"
		"RichText.TextColor"									"ehWhiteColor"
		"RichText.BgColor"										"TransparentBlack"
		"RichText.SelectedTextColor"							"Black"
		"RichText.SelectedBgColor"								"ehAccentColor"
		"ScrollBar.Wide"										"0"
		"ScrollBarSlider.FgColor"								"ehAccentColor"	// nob color
		"ScrollBarSlider.BgColor"								"Blank"	// slider background color
		"SectionedListPanel.HeaderTextColor"					"White"
		"SectionedListPanel.HeaderBgColor"						"Blank"
		"SectionedListPanel.DividerColor"						"Black"
		"SectionedListPanel.TextColor"							"DullWhite"
		"SectionedListPanel.BrightTextColor"					"White"
		"SectionedListPanel.BgColor"							"TransparentBlack"
		"SectionedListPanel.SelectedTextColor"					"Black"
		"SectionedListPanel.SelectedBgColor"					"Orange"
		"SectionedListPanel.OutOfFocusSelectedTextColor"		"Black"
		"SectionedListPanel.OutOfFocusSelectedBgColor"			"255 155 0 128"
		"Slider.NobColor"										"108 108 108 255"
		"Slider.TextColor"										"180 180 180 255"
		"Slider.TrackColor"										"31 31 31 255"
		"Slider.DisabledTextColor1"								"117 117 117 255"
		"Slider.DisabledTextColor2"								"30 30 30 255"
		"TextEntry.TextColor"									"ehWhiteColor"
		"TextEntry.BgColor"										"TransparentBlack"
		"TextEntry.CursorColor"									"OffWhite"
		"TextEntry.DisabledTextColor"							"DullWhite"
		"TextEntry.DisabledBgColor"								"Blank"
		"TextEntry.SelectedTextColor"							"ehWhiteColor"
		"TextEntry.SelectedBgColor"								"ehAccentColor"
		"TextEntry.OutOfFocusSelectedBgColor"					"255 155 0 128"
		"TextEntry.FocusEdgeColor"								"0 0 0 196"
		"ToggleButton.SelectedTextColor"						"White"
		"Tooltip.TextColor"										"0 0 0 196"
		"Tooltip.BgColor"										"Orange"
		"TreeView.BgColor"										"TransparentBlack"
		"WizardSubPanel.BgColor"								"Blank"
		// scheme-specific colors
		"MainMenu.TextColor"									"White"
		"MainMenu.ArmedTextColor"								"200 200 200 255"
		"MainMenu.DepressedTextColor"							"192 186 80 255"
		"MainMenu.MenuItemHeight"								"16"
		"MainMenu.Inset"										"32"
		"MainMenu.Backdrop"										"0 0 0 156"
		"Console.TextColor"										"OffWhite"
		"Console.DevTextColor"									"White"
		"NewGame.TextColor"										"White"
		"NewGame.FillColor"										"0 0 0 255"
		"NewGame.SelectionColor"								"Orange"
		"NewGame.DisabledColor"									"128 128 128 196"
		"TFColors.ChatTextYellow"								"251 235 202 255"
		"TFColors.ChatTextTeamBlue"								"ehBlueColor"
		"TFColors.ChatTextTeamRed"								"ehRedColor"
	}
}